// Generates abi/generated.js from Foundry's build output and deployments/*.json,
// so the keeper never hand-copies ABIs or addresses.
// Runs as part of `pnpm build` and after the local deploy scripts.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url);
const ARTIFACTS = {
  // Uniswap v4 (contracts/out)
  volFeeHookAbi: "out/VolFeeHook.sol/VolFeeHook.json",
  poolManagerAbi: "out/IPoolManager.sol/IPoolManager.json",
  // Algebra Integral v1.2.2 (contracts/algebra/out)
  keeperFeePluginAbi: "algebra/out/KeeperFeePlugin.sol/KeeperFeePlugin.json",
  keeperFeePluginFactoryAbi: "algebra/out/KeeperFeePluginFactory.sol/KeeperFeePluginFactory.json",
  algebraPoolAbi: "algebra/out/IAlgebraPool.sol/IAlgebraPool.json",
};

let src = "// Generated by scripts/generate.mjs from out/, algebra/out/ and deployments/. Do not edit.\n";
for (const [name, file] of Object.entries(ARTIFACTS)) {
  const url = new URL(file, root);
  if (!existsSync(url)) throw new Error(`missing ${file}: run forge build (and forge build in algebra/)`);
  const { abi } = JSON.parse(readFileSync(url, "utf8"));
  src += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)};\n`;
}

// <chainId>.json = Uniswap v4 deployment, <chainId>.algebra.json = Algebra deployment.
const deployments = {};
const algebraDeployments = {};
for (const f of readdirSync(new URL("deployments/", root)).filter((f) => f.endsWith(".json"))) {
  const d = JSON.parse(readFileSync(new URL(`deployments/${f}`, root), "utf8"));
  (f.endsWith(".algebra.json") ? algebraDeployments : deployments)[d.chainId] = d;
}
src += `\nexport const deployments = ${JSON.stringify(deployments, null, 2)};\n`;
src += `\nexport const algebraDeployments = ${JSON.stringify(algebraDeployments, null, 2)};\n`;

writeFileSync(new URL("abi/generated.js", root), src);
console.log(
  `abi/generated.js: ${Object.keys(ARTIFACTS).length} ABIs; v4 chains [${Object.keys(deployments)}], algebra chains [${Object.keys(algebraDeployments)}]`,
);
