// Generates abi/generated.js from Foundry's build output and deployments/*.json,
// so the keeper never hand-copies ABIs or addresses.
// Runs as part of `pnpm build` and after `deploy:local`.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url);
const CONTRACTS = {
  volFeeHookAbi: "VolFeeHook.sol/VolFeeHook.json",
  poolManagerAbi: "IPoolManager.sol/IPoolManager.json",
};

let src = "// Generated by scripts/generate.mjs from out/ and deployments/. Do not edit.\n";
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(readFileSync(new URL(`out/${file}`, root), "utf8"));
  src += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)};\n`;
}

const deployments = {};
for (const f of readdirSync(new URL("deployments/", root)).filter((f) => f.endsWith(".json"))) {
  const d = JSON.parse(readFileSync(new URL(`deployments/${f}`, root), "utf8"));
  deployments[d.chainId] = d;
}
src += `\nexport const deployments = ${JSON.stringify(deployments, null, 2)};\n`;

writeFileSync(new URL("abi/generated.js", root), src);
console.log(`abi/generated.js: ${Object.keys(CONTRACTS).join(", ")}; deployments for chains [${Object.keys(deployments)}]`);
